[server]
host = "blog_blog-backend_1"
port = 8081
database_url = "postgres://postgres:testserver@blog_db_1/blog"

[blog]
name = "ANEP Research"
url = "https://quickn.tech"

[secret]                                 
secret = "quickn_blog"